Models/About.cs
namespace SimpleWebAppMVC.Models
{
    /**
     * About Model
     */
    public class About
    {
        public string AppName   { get; set; }
        public string Copyright { get; set; }
        public string Url       { get; set; }
        public string Version   { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace SimpleWebAppMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(this.RequestId);
    }
}

Models/Task.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SimpleWebAppMVC.Models
{
    /**
     * Task Model 
     */
    public class Task
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public string Id { get; set; }

        [StringLength(50, MinimumLength = 3), Required]
        public string Title { get; set; }

        [StringLength(250)]
        public string Description { get; set; }

        [DataType(DataType.Date)]
        public DateTime Date { get; set; } = DateTime.Today;

        [Required]
        public string Status { get; set; }

        [NotMapped]
        public SelectList StatusCodes { get; } = new SelectList(new List<string> {
            "N/A", "Not Started", "Started", "In Progress", "Almost Done", "Completed"
        });

        public void Update(Task task)
        {
            this.Title       = task.Title;
            this.Description = task.Description;
            this.Date        = task.Date;
            this.Status      = task.Status;
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using SimpleWebAppMVC.Models;
using System.Reflection;

namespace SimpleWebAppMVC.Controllers
{
    /**
     * Home Controller
     */
    public class HomeController : Controller
    {
        // GET /Home/About
        public IActionResult About()
        {
            string          location    = Assembly.GetExecutingAssembly().Location;
            FileVersionInfo versionInfo = FileVersionInfo.GetVersionInfo(location);

            About model = new About
            {
                AppName   = versionInfo.ProductName,
                Copyright = versionInfo.LegalCopyright,
                Version   = ("Version " + versionInfo.ProductVersion)
            };

            return View(model);
        }

        // GET /Home/API
        [HttpGet]
        public IActionResult API()
        {
            ViewData["message_short"] = "Tasks API";

            return View();
        }

        // GET /Home/Error
        public IActionResult Error()
        {
            ErrorViewModel model = new ErrorViewModel
            {
                RequestId = (Activity.Current?.Id ?? HttpContext.TraceIdentifier)
            };

            return View(model);
        }

        // GET [ /, /Home/, /Home/Index ]
        public IActionResult Index()
        {
            ViewData["message_short"] = "Welcome a simple web app!";
            ViewData["message_long"]  = "This simple web app is made using ASP.NET Core 3.1 MVC.";

            return View();
        }
    }
}

Controllers/TasksApiController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;

namespace SimpleWebAppMVC.Controllers
{
    [Produces("application/json")]
    [Route("api/Tasks")]
    public class TasksApiController : Controller
    {
        //private readonly AppDbContext dbContext;

        /**
         * TasksApiController constructor.
         * @param dbCtx Application database context
         */
        public TasksApiController()
        {
           // this.dbContext = dbCtx;
        }

        // GET api/Tasks
        [HttpGet]
        public JsonResult Get()
        {
            return null;
        }

        
       
    }
}

Controllers/TasksController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace SimpleWebAppMVC.Controllers
{
    /**
     * Tasks Controller
     */
    public class TasksController : Controller
    {
        //private readonly AppDbContext dbContext;

        /**
         * TasksController constructor.
         * @param dbCtx Application database context
         */
        public TasksController()
        {
           // this.dbContext = dbCtx;
        }

        /**
         * GET: /Tasks/Create
         */
        [HttpGet]
        public IActionResult Create()
        {
            return View(new Models.Task());
        }

            }
}

Views/Home/API.cshtml
@{
    ViewData["title"] = "Tasks API";
}

<h2>Simple REST Web API</h2>

<div class="jumbotron">
    <h3>@ViewData["message_short"]</h3>

    <p>You can use <a href="https://www.getpostman.com/apps">Postman</a> or <a href="https://curl.haxx.se/docs/manpage.html">curl</a> to test the API from the client side.</p>

    <table class="api">
        <tr><th>Method</th><th>URL</th><th>Description</th></tr>
        <tr><td>GET</td><td><a href="/api/Tasks">/api/Tasks</a></td><td>Returns all tasks</td></tr>
        <tr><td>GET</td><td><a href="/api/Tasks/id">/api/Tasks/id</a></td><td>Returns the task with the specified ID if it exists</td></tr>
        <tr><td>POST</td><td><a href="/api/Tasks">/api/Tasks</a></td><td>Adds a new task</td></tr>
        <tr><td>PUT</td><td><a href="/api/Tasks/id">/api/Tasks/id</a></td><td>Updates the task with the specified ID if it exists</td></tr>
        <tr><td>DELETE</td><td><a href="/api/Tasks/id">/api/Tasks/id</a></td><td>Deletes the task with the specified ID if it exists</td></tr>
    </table>
    <br />

    <table class="api">
        <tr><th>Field</th><th>Required</th><th>Rules</th><th>Example Value</th></tr>
        <tr><td>title</td><td>Yes</td><td>DataType=String, MinLength=3, MaxLength=50</td><td>A short title</td></tr>
        <tr><td>description</td><td>No</td><td>DataType=String, MaxLength=250</td><td>An optional and longer description</td></tr>
        <tr><td>date</td><td>No</td><td>DataType=Date</td><td>2018-08-12T00:00:00</td></tr>
        <tr><td>status</td><td>Yes</td><td>DataType=String</td><td>"N/A", "Not Started", "Started", "In Progress", "Almost Done", "Completed"</td></tr>
    </table>
</div>

Views/Home/About.cshtml
@{
    ViewData["title"] = "About";
}

<h2>@ViewData["title"]</h2>

<div class="jumbotron">
    <h3>@Model.AppName</h3>

    <p>
        @Model.Version<br />
        &copy; @Model.Copyright<br />
        <a href="@Model.Url">@Model.Url</a>
    </p>
</div>

Views/Home/Index.cshtml
@{
    ViewData["title"] = "Home";
}

<h2>Simple Web App MVC</h2>

<div class="jumbotron">
    <h3>@ViewData["message_short"]</h3>
    <p>@ViewData["message_long"]</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewData["title"] - Simple Web App MVC</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>

    <environment exclude="Development">
        <link
            rel="stylesheet"
            href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
            asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
            asp-fallback-test-class="sr-only"
            asp-fallback-test-property="position"
            asp-fallback-test-value="absolute"
        />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Simple Web App MVC</a>
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Tasks" asp-action="Index">Tasks</a></li>
                    <li><a asp-area="" asp-controller="Home"  asp-action="API">API</a></li>
                    <li><a asp-area="" asp-controller="Home"  asp-action="About">About</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
           
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>

    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>

        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Tasks/Create.cshtml
@model SimpleWebAppMVC.Models.Task

@{
    ViewData["Title"] = "Create Task";
}

<h2>@ViewData["Title"]</h2>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" asp-items="@Model.StatusCodes"></select>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div><a asp-action="Index">Back to List</a></div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Tasks/Delete.cshtml
@model SimpleWebAppMVC.Models.Task

@{
    ViewData["Title"] = "Delete Task";
}

<h2>@ViewData["Title"]</h2>
<h3>Are you sure you want to delete this task?</h3>
<hr />

<div class="jumbotron">
    <div>
        <dl class="dl-horizontal">
            <dt>@Html.DisplayNameFor(model => model.Title)</dt>
            <dd>@Html.DisplayFor(model => model.Title)</dd>
            <dt>@Html.DisplayNameFor(model => model.Description)</dt>
            <dd>@Html.DisplayFor(model => model.Description)</dd>
            <dt>@Html.DisplayNameFor(model => model.Date)</dt>
            <dd>@Html.DisplayFor(model => model.Date)</dd>
            <dt>@Html.DisplayNameFor(model => model.Status)</dt>
            <dd>@Html.DisplayFor(model => model.Status)</dd>
        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <input type="submit" value="Delete" class="btn btn-default" />
            </div>
        </form>
    </div>

    <div><a asp-action="Index">Back to List</a></div>
</div>

Views/Tasks/Details.cshtml
@model SimpleWebAppMVC.Models.Task

@{
    ViewData["Title"] = "Task Details";
}

<h2>@ViewData["Title"]</h2>
<hr />

<div class="jumbotron">
    <div>
        <dl class="dl-horizontal">
            <dt>@Html.DisplayNameFor(model => model.Title)</dt>
            <dd>@Html.DisplayFor(model => model.Title)</dd>
            <dt>@Html.DisplayNameFor(model => model.Description)</dt>
            <dd>@Html.DisplayFor(model => model.Description)</dd>
            <dt>@Html.DisplayNameFor(model => model.Date)</dt>
            <dd>@Html.DisplayFor(model => model.Date)</dd>
            <dt>@Html.DisplayNameFor(model => model.Status)</dt>
            <dd>@Html.DisplayFor(model => model.Status)</dd>
        </dl>
    </div>

    <div>
        <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
        <a asp-action="Index">Back to List</a>
    </div>
</div>

Views/Tasks/Edit.cshtml
@model SimpleWebAppMVC.Models.Task

@{
    ViewData["Title"] = "Edit Task";
}

<h2>@ViewData["Title"]</h2>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" asp-items="@Model.StatusCodes"></select>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div><a asp-action="Index">Back to List</a></div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Tasks/Index.cshtml
@model IEnumerable<SimpleWebAppMVC.Models.Task>

@{
    ViewData["Title"] = "Tasks";
}

<h2>@ViewData["Title"]</h2>

<div class="jumbotron">
    <p><a asp-action="Create">Create New</a></p>

    <table class="table">
        <thead>
            <tr>
                <th>@Html.ActionLink("Title",       "Index", new { sort = ViewBag.TitleSortParm })</th>
                <th>@Html.ActionLink("Description", "Index", new { sort = ViewBag.DescriptionSortParm })</th>
                <th>@Html.ActionLink("Date",        "Index", new { sort = ViewBag.DateSortParm })</th>
                <th>@Html.ActionLink("Status",      "Index", new { sort = ViewBag.StatusSortParm })</th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model) {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Title)</td>
                <td>@Html.DisplayFor(modelItem => item.Description)</td>
                <td>@Html.DisplayFor(modelItem => item.Date)</td>
                <td>@Html.DisplayFor(modelItem => item.Status)</td>
                <td>
                    <a asp-action="Edit"    asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete"  asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
            }
        </tbody>
    </table>

    <div>@Html.ActionLink("Download JSON", "GetJSON", new { sort = @ViewData["sortJSON"] })</div>
</div>